export const RESET = 'RESET'
export const SET_CREATED = 'SET_CREATED'
export const SET_ERROR = 'SET_ERROR'
export const SET_VIOLATIONS = 'SET_VIOLATIONS'
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
